name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  call-workflow-ci-php-general:
    name: General
    uses: factorio-item-browser/github-workflows/.github/workflows/ci-php-general.yaml@v1
    with:
      extensions: mbstring, zip

  call-workflow-ci-php-tests:
    name: Tests
    uses: factorio-item-browser/github-workflows/.github/workflows/ci-php-tests.yaml@v1
    with:
      extensions: mbstring, zip
